function gupinit3
% create 3D controls for gup

% Copyright 1996 Anneli Munkholm & Sean M. Brennan.
% Stanford Synchrotron Radiation Laboratory
% Stanford Linear Accelerator Center, Stanford CA 94309
% Bren@slac.stanford.edu

	h=get(gca,'xscale');
	if h(2)=='i'  % as in linear
		xstring='X Log';
	else
		xstring='X Linear';
	end
	h=get(gca,'yscale');
	if h(2)=='i'  % as in linear
		ystring='Y Log';
	else
		ystring='Y Linear';
	end
	h=get(gca,'zscale');
	if h(2)=='i'  % as in linear
		zstring='Z Log';
	else
		zstring='Z Linear';
	end
	xlog = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''xlog'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.18 0.925 0.10 0.05 ],... 
		'String',xstring,... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_xlog'); 
	ylog = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''ylog'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.28 0.925 0.10 0.05 ],... 
		'String',ystring,... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_ylog'); 
	zlog = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''zlog'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.38 0.925 0.10 0.05 ],... 
		'String',zstring,... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_zlog'); 
	xmin = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''xmin'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.17 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_xmin'); 
	xmax = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''xmax'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.29 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_xmax'); 
	ymin = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''ymin'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.41 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_ymin'); 
	ymax = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''ymax'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.53 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_ymax'); 
	zmin = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''zmin'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.65 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_zmin'); 
	zmax = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''zmax'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.77 0.025 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_zmax'); 
	azm = uicontrol(... 
		'BackgroundColor',[ .7 .7 .7 ],... 
		'CallBack','gup(''azm'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.48 .925 0.2 0.045 ],... 
		'Min',[-180],... 
		'Max',[180],... 
		'Value',[-35],...
		'Style','slider',... 
		'Visible','on',... 
		'tag','gup_azm'); 
	elv = uicontrol(... 
		'BackgroundColor',[.7 .7 .7],... 
		'CallBack','gup(''elv'');',... 		
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.68 .925 0.2 0.045 ],... 
		'Min',[-90],... 
		'Max',[90],... 
		'Value',[30],...
		'Style','slider',... 
		'Visible','on',... 
		'tag','gup_elv');
	% get backfround color of current figure
	bgcolor=get(gcf,'color');
	if sum(bgcolor)>1, txtcolor=[0 0 0]; else txtcolor=[1 1 1]; end 
	t_xmin = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[0.17 0.0 0.11 0.03],... 
		'Style','text',... 
		'String','Xmin',...
		'Visible','on',... 
		'tag','gupt_xmin'); 
	t_xmax = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.29 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Xmax',...
		'Visible','on',... 
		'tag','gupt_xmax'); 
	t_ymin = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.41 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Ymin',...
		'Visible','on',... 
		'tag','gupt_ymin'); 
	t_ymax = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.53 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Ymax',...
		'Visible','on',... 
		'tag','gupt_ymax'); 
	t_zmin = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.65 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Zmin',...
		'Visible','on',... 
		'tag','gupt_zmin'); 
	t_zmax = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.77 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Zmax',...
		'Visible','on',... 
		'tag','gupt_zmax'); 
	t_azm = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.5 .97 0.1 0.03 ],... 
		'Style','text',... 
		'String','Azimuth',...
		'Visible','on',... 
		'tag','gupt_azm'); 
	t_elv = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.705 .97 0.1 0.03 ],... 
		'Style','text',... 
		'String','Elevation',...
		'Visible','on',... 
		'tag','gupt_elv'); 
	txt_azm = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.6 .97 0.07 0.03 ],... 
		'Style','text',... 
		'String',' ',...
		'Visible','on',... 
		'tag','guptxt_azm'); 
	txt_elv = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.80 .97 0.05 0.03 ],... 
		'Style','text',... 
		'String',' ',...
		'Visible','on',... 
		'tag','guptxt_elv'); 
	guplmts;
	[az,el]=view;
	if az>180, az=az-360; end
	set(findobj(gcf,'tag','gup_azm'),'Value',az);
	set(findobj(gcf,'tag','gup_elv'),'Value',el);
	set(findobj(gcf,'tag','guptxt_azm'),'String',int2str(round(az)));
	set(findobj(gcf,'tag','guptxt_elv'),'String',int2str(round(el)));

