function gupinit
% create controls for gup

% Copyright 1996 Anneli Munkholm & Sean M. Brennan.
% Stanford Synchrotron Radiation Laboratory
% Stanford Linear Accelerator Center, Stanford CA 94309
% Bren@slac.stanford.edu

	h=get(gca,'xscale');
	if h(2)=='i'  % as in linear
		xstring='X Log';
	else
		xstring='X Linear';
	end
	h=get(gca,'yscale');
	if h(2)=='i'  % as in linear
		ystring='Y Log';
	else
		ystring='Y Linear';
	end
	xlog = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''xlog'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.08 0.02 0.10 0.05 ],... 
		'String',xstring,... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_xlog'); 
	ylog = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''ylog'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.18 0.02 0.10 0.05 ],... 
		'String',ystring,... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_ylog'); 
	xmin = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''xmin'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.29 0.02 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_xmin'); 
	xmax = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''xmax'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.41 0.02 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_xmax'); 
	ymin = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''ymin'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.53 0.02 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_ymin'); 
	ymax = uicontrol(... 
		'BackgroundColor',[ 1 1 1],... 
		'CallBack','gup(''ymax'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.65 0.02 0.11 0.05 ],... 
		'String',' ',... 
		'Style','edit',... 
		'Visible','on',... 
		'tag','gup_ymax'); 
	zum = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''zum'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.77 0.02 0.10 0.05 ],... 
		'String','Zoom',... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_zum'); 
	zout = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','gup(''zout'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.87 0.02 0.10 0.05 ],... 
		'String','Zout',... 
		'Style','pushbutton',... 
		'Visible','on',... 
		'tag','gup_zout'); 
	% get background color of current figure
	bgcolor=get(gcf,'color');
	if sum(bgcolor)>1, txtcolor=[0 0 0]; else txtcolor=[1 1 1]; end
	t_xmin = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.29 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Xmin',...
		'Visible','on',... 
		'tag','gupt_xmin'); 
	t_xmax = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.41 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Xmax',...
		'Visible','on',... 
		'tag','gupt_xmax'); 
	t_ymin = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.53 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Ymin',...
		'Visible','on',... 
		'tag','gupt_ymin'); 
	t_ymax = uicontrol(... 
		'BackgroundColor',bgcolor,... 
		'ForegroundColor',txtcolor,... 
		'Units','normalized',... 
		'Position',[ 0.65 0.0 0.11 0.03 ],... 
		'Style','text',... 
		'String','Ymax',...
		'Visible','on',... 
		'tag','gupt_ymax'); 
	guplmts;
	set(gcf,'WindowButtonMotionFcn','cursmode(''gup'')');
